config:
    modelType: regression
    modelName: "GCN"
    filePath: "/content/dataset.csv"
    optimizer: optim.Adam
    learning_rate: 0.0001
    batch_size: 10
    splits: [0.6,0.2,0.20]
    epochs: 1
    gpus: 1

