config:
  type: generator
  modelName: CharRNN
  filePath: "/home/bayeslabs/molFlash/molflash/generator/charRNN/train.csv"
  preprocessing: 
  loss_fn: nn.CrossEntropyLoss()
  learning_rate: 0.001
  batch_size: 32
  epochs: 5
  gpus: 1
  logger:
  optimizer: optim.Adam
  hidden: 128
  num_layers: 2
  dropout: 0.1
  splits: [0.7,0.15,0.15]

