config:
    type: Classification
    modelName: EMN
    filePath: "/home/trinity/Bayes-Labs/NEW-CKPTS-21012021/bbb/bbb.csv"
    optimizer: optim.Adam
    learning_rate: 0.0001
    batch_size: 32
    splits: [0.7,0.15,0.15]
    epochs: 300
    gpus: 1
