config:
  type: Generation
  modelName: LSTM
  filePath: "/content/logP_adme.csv"
  preprocessing: input_data
  loss_fn: nn.CrossEntropyLoss()
  splits: [0.7,0.15,0.15]
  lr: 0.001
  batch_size: 32
  epochs: 10
  gpus: 1
  metrics: F1
  logger:
  optimizer: optim.Adam
  hidden_size: 512
  num_layers: 2

  enc_emb_size: 300
  enc_hid_size: 512
  enc_n_layers: 2
  enc_drop: 0.1

  dec_emb_size: 300
  dec_hid_size: 512
  dec_n_layers: 2
  dec_drop: 0.1
  
