config:
  type: Generation
  modelName: LSTM
  filePath: "/home/bayeslabs/molFlash/molflash/generator/Seq2Seq/data.csv"
  preprocessing: input_data
  loss_fn: nn.CrossEntropyLoss()
  splits: [0.7,0.15,0.15]
  lr: 0.0001
  batch_size: 8
  epochs: 2
  gpus: 1
  metrics: F1
  logger:
  optimizer: optim.Adam
  hidden_size: 512
  num_layers: 4

  enc_emb_size: 300
  enc_hid_size: 512
  enc_n_layers: 4
  enc_drop: 0.2

  dec_emb_size: 300
  dec_hid_size: 512
  dec_n_layers: 4
  dec_drop: 0.2
  
