config:
  type: Classification
  modelName: GCN
  filePath: "/home/bayeslabs/New_Arch/proppred/bbb.csv"
  optimizer: optim.Adam
  learning_rate: 0.001
  batch_size: 16
  val_split: 0.3
  epochs: 5
  params: {'in_channel': 40,
              'hid1': 128,
              'hid2': 256,
              'hid3': 128,
              'lin1': 512,
              'lin2': 128,
              'out': 1,
              'drop': 0.5,
              }
  