config:
  type: Generation
  modelName: GAN
  filePath: "/home/bayeslabs/New_Arch/latent-gan/data/rationales.smi"
  preprocessing: 
  loss_fn: nn.CrossEntropyLoss()
  splits: [0.7,0.15,0.15]
  lr: 0.001
  batch_size: 10
  epochs: 200
  gpus: 1
  logger:
  optimizer: torch.optim.Adam
  dropout: 0
  latent_dim: 512


  
