config:
  type: retrosynthesis
  modelName: Transformer
  filePath: "/home/bayeslabs/molFlash/molflash/retrosynthesis/Seq2Seq/Transformer/data.csv"
  preprocessing: input_data
  loss_fn: nn.CrossEntropyLoss(ignore_index = src_pad_index)
  metrics: F1(num_classes = dm.reactant_vocab_size,mdmc_average='samplewise')
  batch_size: 16
  epochs: 30
  gpus: 1
  logger:
  optimizer: optim.Adam

  emb_size: 64
  hid_size: 256
  n_layers: 3
  dropout: 0.1
  n_heads: 8
  split: [0.8,0.1,0.1]

  
