config:
  type: Generation
  modelName: transformer
  filePath: "/home/bayeslabs/molFlash/molflash/generator/transformer/mmp_prop.csv"
  preprocessing: input_data
  loss_fn: nn.CrossEntropyLoss(ignore_index = 0)
  splits: [0.7,0.15,0.15]
  lr: 0.001
  batch_size: 64
  epochs: 3
  gpus: 1
  metrics: F1
  logger:
  optimizer: optim.Adam
  num_layers: 6
  hidden_dim: 256
  feedforward_dim: 2048
  no_heads: 8
  dropout: 0